remote_theme: coursweb/jk-theme
title: AP-IMD â€“ ID451
description: Cours Projets IMD - Semestre 2
lang: fr-FR
# markdown: GFM
robots: noindex, nofollow
# menu 
chapters:
 - title: Projet IMD
   url: https://id451.ch/
# - title: RÃ©fÃ©rence CSS
#   url: https://cours-web.ch/css/
# - title: Infos IMD
#   url: https://eracom.ch/informations-eleves-id/
# - title: Plan de formation
#   url: https://code.eracom-pedagogique.ch/formation-imd-2020/   
# - title: Fontes IMD
#   url: https://code.eracom-pedagogique.ch/fontes-imd/  
 - title: ğŸ€ Teams
   url: https://teams.microsoft.com/l/channel/19%3Acec0ec05e7c3401288886fc9a79da0a9%40thread.tacv2/Projets%20IMD?groupId=3fb4d0ee-acb4-42bb-b635-53124b432c58&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1&openInBrowser=true
 - title: ğŸŒ Sharepoint
   url: https://eduvaud.sharepoint.com/:f:/r/sites/ERACOM_2526_ID451_Teams/Documents%20partages/Projets%20IMD?csf=1&web=1&e=rtnVIv
# - title: ğŸ§  Podsie
#   url: https://student.podsie.org/
# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2026</li></ul>
footer_col_2: <ul class="social-media-list">
    <li><a href="https://www.figma.com/files/team/1534469695620406884/all-projects">ğŸ’ Figma</a></li>
  <li><a href="https://teams.microsoft.com/l/channel/19%3Acec0ec05e7c3401288886fc9a79da0a9%40thread.tacv2/Projets%20IMD?groupId=3fb4d0ee-acb4-42bb-b635-53124b432c58&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1">ğŸ€ Teams</a></li>
  <li><a href="https://eracom-imd451.github.io/projets-imd-s2/">ğŸ™ Github</a></li>
  </ul>
